### PR TITLE
Add contributions/edc_byoc_tutorial.ipynb (ID: 95a4fc78-bc7e-4dc8-b4f2-fdc1f8559a03)

### PR DESCRIPTION
**Pull request by eurodatacube-submissions**
{"path": "contributions/edc_byoc_tutorial.ipynb", "id": "95a4fc78-bc7e-4dc8-b4f2-fdc1f8559a03", "license": null, "name": "How to bring your own data to EDC: Using Sentinel Hub Python package", "requirements": ["eurodatacube", "eoxhub", "eoxhub"], "tags": ["Jupyter", "On-the-fly", "Sentinel Hub", "Sentinel Data", "EO Data"], "tosAgree": true, "type": "Jupyter Notebook", "version": "0.0.3", "description": "A BYOC tutorial using Sentinel Hub Python package", "authors": [{"id": "84ffd9e5-7b17-4608-8346-5f29f1ce711f", "name": "chung.horng@sinergise.com"}]}

### CODE REVIEW

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [5]":
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 config.aws_access_key_id = os.environ["AWS_ACCESS_KEY_ID"]
      2 config.aws_secret_access_key = os.environ["AWS_SECRET_ACCESS_KEY"]

File /opt/conda/envs/edc-default-2022.07-00/lib/python3.9/os.py:679, in _Environ.__getitem__(self, key)
    676     value = self._data[self.encodekey(key)]
    677 except KeyError:
    678     # raise KeyError with the original key value
--> 679     raise KeyError(key) from None
    680 return self.decodevalue(value)

KeyError: 'AWS_ACCESS_KEY_ID'

```

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [5]":
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 config.aws_access_key_id = os.environ["AWS_ACCESS_KEY_ID"]
      2 config.aws_secret_access_key = os.environ["AWS_SECRET_ACCESS_KEY"]

File /opt/conda/envs/edc-default-2022.07-00/lib/python3.9/os.py:679, in _Environ.__getitem__(self, key)
    676     value = self._data[self.encodekey(key)]
    677 except KeyError:
    678     # raise KeyError with the original key value
--> 679     raise KeyError(key) from None
    680 return self.decodevalue(value)

KeyError: 'AWS_ACCESS_KEY_ID'

```

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [5]":
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 config.aws_access_key_id = os.environ["AWS_ACCESS_KEY_ID"]
      2 config.aws_secret_access_key = os.environ["AWS_SECRET_ACCESS_KEY"]

File /opt/conda/envs/edc-default-2022.07-00/lib/python3.9/os.py:679, in _Environ.__getitem__(self, key)
    676     value = self._data[self.encodekey(key)]
    677 except KeyError:
    678     # raise KeyError with the original key value
--> 679     raise KeyError(key) from None
    680 return self.decodevalue(value)

KeyError: 'AWS_ACCESS_KEY_ID'

```

**Comment by totycro** [comment]
Merged manually

**Pull request closed without merging**
