### PR TITLE
Add contributions/EDC_xcube_generator_service.ipynb (ID: 01c63259-e678-427d-8f4a-6238219c0925)

### PR DESCRIPTION
**Pull request by eurodatacube-submissions**
{"path": "contributions/EDC_xcube_generator_service.ipynb", "id": "01c63259-e678-427d-8f4a-6238219c0925", "license": null, "name": "Introduction on how to use xcube generator service", "requirements": ["eurodatacube-xcube-gen", "eoxhub"], "tags": ["Analysis-Ready Data", "Download Service", "EO Data", "Getting started", "Jupyter", "Sentinel Data", "xcube"], "tosAgree": true, "type": "Jupyter Notebook", "version": "0.0.2", "description": "Generate cubes from different data stores offered by EDC.", "authors": [{"id": "139b9f28-6757-4ffa-8345-3f658eb33850", "name": "alicja.balfanz@brockmann-consult.de"}]}

### CODE REVIEW

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [28]":
---------------------------------------------------------------------------
CubeGeneratorError                        Traceback (most recent call last)
<ipython-input-28-778b889ab15c> in <module>
----> 1 cube_id = gen.generate_cube()
      2 cube_id

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/xcube/core/gen2/service/generator.py in generate_cube(self)
    123                 response = requests.get(self.endpoint_op(f'cubegens/{cubegen_id}'),
    124                                         headers=self.auth_headers)
--> 125                 result = self._get_cube_generation_result(response)
    126                 if result.status.succeeded:
    127                     return self._get_data_id(cubegen_id + '.zarr')

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/xcube/core/gen2/service/generator.py in _get_cube_generation_result(self, response, request_data)
    152                                 if isinstance(item, dict) and 'message' in item]
    153                 message = f'{message}: {": ".join(sub_messages)}'
--> 154             raise CubeGeneratorError(message,
    155                                      remote_output=result.output)
    156         return result

CubeGeneratorError: Cube generation failed

```

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [28]":
---------------------------------------------------------------------------
CubeGeneratorError                        Traceback (most recent call last)
<ipython-input-28-778b889ab15c> in <module>
----> 1 cube_id = gen.generate_cube()
      2 cube_id

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/xcube/core/gen2/service/generator.py in generate_cube(self)
    123                 response = requests.get(self.endpoint_op(f'cubegens/{cubegen_id}'),
    124                                         headers=self.auth_headers)
--> 125                 result = self._get_cube_generation_result(response)
    126                 if result.status.succeeded:
    127                     return self._get_data_id(cubegen_id + '.zarr')

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/xcube/core/gen2/service/generator.py in _get_cube_generation_result(self, response, request_data)
    152                                 if isinstance(item, dict) and 'message' in item]
    153                 message = f'{message}: {": ".join(sub_messages)}'
--> 154             raise CubeGeneratorError(message,
    155                                      remote_output=result.output)
    156         return result

CubeGeneratorError: Cube generation failed

```

**Comment by totycro** [comment]
I've contacted the author about the error.

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Pull request merged**
