### PR TITLE
add final IGARSS 2022 notebooks

### PR DESCRIPTION
**Pull request by Schpidi**

### CODE REVIEW

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [34]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [34], in <cell line: 125>()
    122     except Exception:
    123         print("Issue parsing response")
--> 125 print(respjson)
    126 respjson

NameError: name 'respjson' is not defined

```

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [2]":
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [2], in <cell line: 5>()
      3 import os
      4 import numpy
----> 5 import wget
      6 import shapely
      7 import rasterio

ModuleNotFoundError: No module named 'wget'

```

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [2]":
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [2], in <cell line: 5>()
      3 import os
      4 import numpy
----> 5 import wget
      6 import shapely
      7 import rasterio

ModuleNotFoundError: No module named 'wget'

```

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by totycro** [comment]
Relevant commit was merged manually to avoid unintended automatic executions.

**Pull request closed without merging**
