### PR TITLE
updated geodb notebooks to reflect newest implementations

### PR DESCRIPTION
**Pull request by AliceBalfanz**
This PR makes an update to the geodb notebooks to reflect the newest implemetations in geodb version 1.0.4

### CODE REVIEW

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [8]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [8], in <cell line: 1>()
----> 1 geodb.get_event_log('land_use')

AttributeError: 'GeoDBClient' object has no attribute 'get_event_log'

```

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [6]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 geodb.get_geodb_sql_version()

AttributeError: 'GeoDBClient' object has no attribute 'get_geodb_sql_version'

```

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [6]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 geodb.get_geodb_sql_version()

AttributeError: 'GeoDBClient' object has no attribute 'get_geodb_sql_version'

```

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [6]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 geodb.get_geodb_sql_version()

AttributeError: 'GeoDBClient' object has no attribute 'get_geodb_sql_version'

```

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [8]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [8], in <cell line: 1>()
----> 1 geodb.get_event_log('land_use')

AttributeError: 'GeoDBClient' object has no attribute 'get_event_log'

```

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [8]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [8], in <cell line: 1>()
----> 1 geodb.get_event_log('land_use')

AttributeError: 'GeoDBClient' object has no attribute 'get_event_log'

```

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [6]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 geodb.get_geodb_sql_version()

AttributeError: 'GeoDBClient' object has no attribute 'get_geodb_sql_version'

```

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [6]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 geodb.get_geodb_sql_version()

AttributeError: 'GeoDBClient' object has no attribute 'get_geodb_sql_version'

```

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [8]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [8], in <cell line: 1>()
----> 1 geodb.get_event_log('land_use')

AttributeError: 'GeoDBClient' object has no attribute 'get_event_log'

```

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by totycro** [comment]
I've merged the relevant commit directly, the other commits were autogenerated validation with the previous base image version.

**Pull request closed without merging**
