### PR TITLE
Add contributions/HowToLULC_batch.ipynb (ID: 3c264153-2bfc-42fa-9a7a-2276c88755f8)

### PR DESCRIPTION
**Pull request by eurodatacube-submissions**
{"path": "contributions/HowToLULC_batch.ipynb", "id": "3c264153-2bfc-42fa-9a7a-2276c88755f8", "license": null, "name": "Batch Processing with eo-learn", "requirements": ["eurodatacube"], "tags": ["EO Data", "Jupyter", "Machine Learning", "Land-Use-Classification", "Mass Processing", "Sentinel Data", "Sentinel Hub"], "tosAgree": true, "type": "Jupyter Notebook", "version": "0.0.1", "description": "Replace part of the eo-learn workflow with Batch Processing", "authors": [{"id": "a2b85af8-6b99-4fa2-acf6-e87d74e40431", "name": "maxim.lamare@sinergise.com"}]}

### CODE REVIEW

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [7]":
---------------------------------------------------------------------------
CPLE_OpenFailedError                      Traceback (most recent call last)
fiona/_shim.pyx in fiona._shim.gdal_open_vector()

fiona/_err.pyx in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: data/ljubljana.geojson: No such file or directory

During handling of the above exception, another exception occurred:

DriverError                               Traceback (most recent call last)
<ipython-input-7-b9adaa1d59dc> in <module>
      3 
      4 # Load geojson file
----> 5 country = gpd.read_file(INPUT_DATA.joinpath('ljubljana.geojson'))
      6 
      7 # Apply a 500m buffer to the shape

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/geopandas/io/file.py in read_file(filename, bbox, **kwargs)
     74 
     75     with fiona_env():
---> 76         with reader(path_or_bytes, **kwargs) as features:
     77 
     78             # In a future Fiona release the crs attribute of features will

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/fiona/env.py in wrapper(*args, **kwargs)
    395     def wrapper(*args, **kwargs):
    396         if local._env:
--> 397             return f(*args, **kwargs)
    398         else:
    399             if isinstance(args[0], str):

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/fiona/__init__.py in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
    251         if mode in ('a', 'r'):
    252             c = Collection(path, mode, driver=driver, encoding=encoding,
--> 253                            layer=layer, enabled_drivers=enabled_drivers, **kwargs)
    254         elif mode == 'w':
    255             if schema:

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/fiona/collection.py in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
    157             if self.mode == 'r':
    158                 self.session = Session()
--> 159                 self.session.start(self, **kwargs)
    160             elif self.mode in ('a', 'w'):
    161                 self.session = WritingSession()

fiona/ogrext.pyx in fiona.ogrext.Session.start()

fiona/_shim.pyx in fiona._shim.gdal_open_vector()

DriverError: data/ljubljana.geojson: No such file or directory

```

**Comment by totycro** [comment]
i merged the first commit manually because we can't execute the notebook.

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [7]":
---------------------------------------------------------------------------
CPLE_OpenFailedError                      Traceback (most recent call last)
fiona/_shim.pyx in fiona._shim.gdal_open_vector()

fiona/_err.pyx in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: data/ljubljana.geojson: No such file or directory

During handling of the above exception, another exception occurred:

DriverError                               Traceback (most recent call last)
<ipython-input-7-b9adaa1d59dc> in <module>
      3 
      4 # Load geojson file
----> 5 country = gpd.read_file(INPUT_DATA.joinpath('ljubljana.geojson'))
      6 
      7 # Apply a 500m buffer to the shape

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/geopandas/io/file.py in read_file(filename, bbox, **kwargs)
     74 
     75     with fiona_env():
---> 76         with reader(path_or_bytes, **kwargs) as features:
     77 
     78             # In a future Fiona release the crs attribute of features will

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/fiona/env.py in wrapper(*args, **kwargs)
    395     def wrapper(*args, **kwargs):
    396         if local._env:
--> 397             return f(*args, **kwargs)
    398         else:
    399             if isinstance(args[0], str):

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/fiona/__init__.py in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
    251         if mode in ('a', 'r'):
    252             c = Collection(path, mode, driver=driver, encoding=encoding,
--> 253                            layer=layer, enabled_drivers=enabled_drivers, **kwargs)
    254         elif mode == 'w':
    255             if schema:

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/fiona/collection.py in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
    157             if self.mode == 'r':
    158                 self.session = Session()
--> 159                 self.session.start(self, **kwargs)
    160             elif self.mode in ('a', 'w'):
    161                 self.session = WritingSession()

fiona/ogrext.pyx in fiona.ogrext.Session.start()

fiona/_shim.pyx in fiona._shim.gdal_open_vector()

DriverError: data/ljubljana.geojson: No such file or directory

```

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [7]":
---------------------------------------------------------------------------
CPLE_OpenFailedError                      Traceback (most recent call last)
fiona/_shim.pyx in fiona._shim.gdal_open_vector()

fiona/_err.pyx in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: data/ljubljana.geojson: No such file or directory

During handling of the above exception, another exception occurred:

DriverError                               Traceback (most recent call last)
<ipython-input-7-b9adaa1d59dc> in <module>
      3 
      4 # Load geojson file
----> 5 country = gpd.read_file(INPUT_DATA.joinpath('ljubljana.geojson'))
      6 
      7 # Apply a 500m buffer to the shape

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/geopandas/io/file.py in read_file(filename, bbox, **kwargs)
     74 
     75     with fiona_env():
---> 76         with reader(path_or_bytes, **kwargs) as features:
     77 
     78             # In a future Fiona release the crs attribute of features will

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/fiona/env.py in wrapper(*args, **kwargs)
    395     def wrapper(*args, **kwargs):
    396         if local._env:
--> 397             return f(*args, **kwargs)
    398         else:
    399             if isinstance(args[0], str):

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/fiona/__init__.py in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
    251         if mode in ('a', 'r'):
    252             c = Collection(path, mode, driver=driver, encoding=encoding,
--> 253                            layer=layer, enabled_drivers=enabled_drivers, **kwargs)
    254         elif mode == 'w':
    255             if schema:

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/fiona/collection.py in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
    157             if self.mode == 'r':
    158                 self.session = Session()
--> 159                 self.session.start(self, **kwargs)
    160             elif self.mode in ('a', 'w'):
    161                 self.session = WritingSession()

fiona/ogrext.pyx in fiona.ogrext.Session.start()

fiona/_shim.pyx in fiona._shim.gdal_open_vector()

DriverError: data/ljubljana.geojson: No such file or directory

```

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [7]":
---------------------------------------------------------------------------
CPLE_OpenFailedError                      Traceback (most recent call last)
fiona/_shim.pyx in fiona._shim.gdal_open_vector()

fiona/_err.pyx in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: data/ljubljana.geojson: No such file or directory

During handling of the above exception, another exception occurred:

DriverError                               Traceback (most recent call last)
<ipython-input-7-b9adaa1d59dc> in <module>
      3 
      4 # Load geojson file
----> 5 country = gpd.read_file(INPUT_DATA.joinpath('ljubljana.geojson'))
      6 
      7 # Apply a 500m buffer to the shape

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/geopandas/io/file.py in read_file(filename, bbox, **kwargs)
     74 
     75     with fiona_env():
---> 76         with reader(path_or_bytes, **kwargs) as features:
     77 
     78             # In a future Fiona release the crs attribute of features will

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/fiona/env.py in wrapper(*args, **kwargs)
    395     def wrapper(*args, **kwargs):
    396         if local._env:
--> 397             return f(*args, **kwargs)
    398         else:
    399             if isinstance(args[0], str):

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/fiona/__init__.py in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
    251         if mode in ('a', 'r'):
    252             c = Collection(path, mode, driver=driver, encoding=encoding,
--> 253                            layer=layer, enabled_drivers=enabled_drivers, **kwargs)
    254         elif mode == 'w':
    255             if schema:

/opt/conda/envs/eurodatacube-0.20.1/lib/python3.7/site-packages/fiona/collection.py in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
    157             if self.mode == 'r':
    158                 self.session = Session()
--> 159                 self.session.start(self, **kwargs)
    160             elif self.mode in ('a', 'w'):
    161                 self.session = WritingSession()

fiona/ogrext.pyx in fiona.ogrext.Session.start()

fiona/_shim.pyx in fiona._shim.gdal_open_vector()

DriverError: data/ljubljana.geojson: No such file or directory

```

**Pull request closed without merging**
