### PR TITLE
Add contributions/ESDL_EDC_v0.1.ipynb (ID: dc342790-b2e9-4928-bc99-d85f14ab8745)

### PR DESCRIPTION
**Pull request by eurodatacube-submissions**
{"path": "contributions/ESDL_EDC_v0.1.ipynb", "id": "dc342790-b2e9-4928-bc99-d85f14ab8745", "license": null, "name": "Earth System Data Lab", "requirements": ["eoxhub"], "tags": ["xcube", "Analysis-Ready Data"], "tosAgree": true, "type": "Jupyter Notebook", "version": "0.2", "description": "Demonstrating access to Earth System Data Cube in EDC", "authors": [{"id": "139b9f28-6757-4ffa-8345-3f658eb33850", "name": "alicja.balfanz@brockmann-consult.de"}]}

### CODE REVIEW

**Comment by eurodatacube-submissions** [comment]
:x: Execution timed out after 600 seconds

**Comment by eurodatacube-submissions** [comment]
:x: Execution timed out after 600 seconds

**Comment by totycro** [comment]
I've contacted the author about this on 2021-06-07 but no response so far.

**Comment by totycro** [comment]
A newer version has now been accepted

**Pull request closed without merging**
