### PR TITLE
Add contributions/AIREO_pilot_dataset_-_Biomass_Forest_Observation_System.ipynb (ID: a8f41fdb-b43b-428b-9919-5616ec0420bb)

### PR DESCRIPTION
**Pull request by eurodatacube-submissions**
{"path": "contributions/AIREO_pilot_dataset_-_Biomass_Forest_Observation_System.ipynb", "id": "a8f41fdb-b43b-428b-9919-5616ec0420bb", "license": null, "name": "AIREO pilot dataset - Biomass (Forest Observation System)", "requirements": ["eurodatacube", "eoxhub"], "tags": ["Analysis-Ready Data", "EO Data", "Jupyter", "Machine Learning", "Sentinel Data", "Sentinel Hub"], "tosAgree": true, "type": "Jupyter Notebook", "version": "0.1.3", "description": "Use of aireo_lib library as part of AIREO project", "authors": [{"id": "a7f80638-e89a-4349-9cc7-7ed6ec2d79b7", "name": "AIREO team"}]}

### CODE REVIEW

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
SSLCertVerificationError                  Traceback (most recent call last)
/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1353             try:
-> 1354                 h.request(req.get_method(), req.selector, req.data, headers,
   1355                           encode_chunked=req.has_header('Transfer-encoding'))

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1251         """Send a complete request to the server."""
-> 1252         self._send_request(method, url, body, headers, encode_chunked)
   1253 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1297             body = _encode(body, 'body')
-> 1298         self.endheaders(body, encode_chunked=encode_chunked)
   1299 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in endheaders(self, message_body, encode_chunked)
   1246             raise CannotSendHeader()
-> 1247         self._send_output(message_body, encode_chunked=encode_chunked)
   1248 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in _send_output(self, message_body, encode_chunked)
   1006         del self._buffer[:]
-> 1007         self.send(msg)
   1008 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in send(self, data)
    946             if self.auto_open:
--> 947                 self.connect()
    948             else:

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in connect(self)
   1420 
-> 1421             self.sock = self._context.wrap_socket(self.sock,
   1422                                                   server_hostname=server_hostname)

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    499         # ctx._wrap_socket()
--> 500         return self.sslsocket_class._create(
    501             sock=sock,

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/ssl.py in _create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
   1039                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
-> 1040                     self.do_handshake()
   1041             except (OSError, ValueError):

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/ssl.py in do_handshake(self, block)
   1308                 self.settimeout(None)
-> 1309             self._sslobj.do_handshake()
   1310         finally:

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
<ipython-input-4-5b595d75abc1> in <module>
      1 #Pull Biomass excel sheet
      2 path = ('https://forest-observation-system.net/Data/FOS_Plots_v2019.04.10.xlsx')
----> 3 df = pd.read_excel (path)
      4 df.keys()
      5 gdf = gp.GeoDataFrame(

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    297                 )
    298                 warnings.warn(msg, FutureWarning, stacklevel=stacklevel)
--> 299             return func(*args, **kwargs)
    300 
    301         return wrapper

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/excel/_base.py in read_excel(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, thousands, comment, skipfooter, convert_float, mangle_dupe_cols, storage_options)
    334     if not isinstance(io, ExcelFile):
    335         should_close = True
--> 336         io = ExcelFile(io, storage_options=storage_options, engine=engine)
    337     elif engine and engine != io.engine:
    338         raise ValueError(

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/excel/_base.py in __init__(self, path_or_buffer, engine, storage_options)
   1069                 ext = "xls"
   1070             else:
-> 1071                 ext = inspect_excel_format(
   1072                     content=path_or_buffer, storage_options=storage_options
   1073                 )

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/excel/_base.py in inspect_excel_format(path, content, storage_options)
    947     assert content_or_path is not None
    948 
--> 949     with get_handle(
    950         content_or_path, "rb", storage_options=storage_options, is_text=False
    951     ) as handle:

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/common.py in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    556 
    557     # open URLs
--> 558     ioargs = _get_filepath_or_buffer(
    559         path_or_buf,
    560         encoding=encoding,

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/common.py in _get_filepath_or_buffer(filepath_or_buffer, encoding, compression, mode, storage_options)
    287                 "storage_options passed with file object or non-fsspec file path"
    288             )
--> 289         req = urlopen(filepath_or_buffer)
    290         content_encoding = req.headers.get("Content-Encoding", None)
    291         if content_encoding == "gzip":

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/common.py in urlopen(*args, **kwargs)
    193     import urllib.request
    194 
--> 195     return urllib.request.urlopen(*args, **kwargs)
    196 
    197 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in open(self, fullurl, data, timeout)
    523 
    524         sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> 525         response = self._open(req, data)
    526 
    527         # post-process response

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in _open(self, req, data)
    540 
    541         protocol = req.type
--> 542         result = self._call_chain(self.handle_open, protocol, protocol +
    543                                   '_open', req)
    544         if result:

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in https_open(self, req)
   1395 
   1396         def https_open(self, req):
-> 1397             return self.do_open(http.client.HTTPSConnection, req,
   1398                 context=self._context, check_hostname=self._check_hostname)
   1399 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1355                           encode_chunked=req.has_header('Transfer-encoding'))
   1356             except OSError as err: # timeout error
-> 1357                 raise URLError(err)
   1358             r = h.getresponse()
   1359         except:

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)>

```

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
SSLCertVerificationError                  Traceback (most recent call last)
/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1353             try:
-> 1354                 h.request(req.get_method(), req.selector, req.data, headers,
   1355                           encode_chunked=req.has_header('Transfer-encoding'))

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1251         """Send a complete request to the server."""
-> 1252         self._send_request(method, url, body, headers, encode_chunked)
   1253 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1297             body = _encode(body, 'body')
-> 1298         self.endheaders(body, encode_chunked=encode_chunked)
   1299 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in endheaders(self, message_body, encode_chunked)
   1246             raise CannotSendHeader()
-> 1247         self._send_output(message_body, encode_chunked=encode_chunked)
   1248 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in _send_output(self, message_body, encode_chunked)
   1006         del self._buffer[:]
-> 1007         self.send(msg)
   1008 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in send(self, data)
    946             if self.auto_open:
--> 947                 self.connect()
    948             else:

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in connect(self)
   1420 
-> 1421             self.sock = self._context.wrap_socket(self.sock,
   1422                                                   server_hostname=server_hostname)

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    499         # ctx._wrap_socket()
--> 500         return self.sslsocket_class._create(
    501             sock=sock,

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/ssl.py in _create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
   1039                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
-> 1040                     self.do_handshake()
   1041             except (OSError, ValueError):

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/ssl.py in do_handshake(self, block)
   1308                 self.settimeout(None)
-> 1309             self._sslobj.do_handshake()
   1310         finally:

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
<ipython-input-4-5b595d75abc1> in <module>
      1 #Pull Biomass excel sheet
      2 path = ('https://forest-observation-system.net/Data/FOS_Plots_v2019.04.10.xlsx')
----> 3 df = pd.read_excel (path)
      4 df.keys()
      5 gdf = gp.GeoDataFrame(

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    297                 )
    298                 warnings.warn(msg, FutureWarning, stacklevel=stacklevel)
--> 299             return func(*args, **kwargs)
    300 
    301         return wrapper

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/excel/_base.py in read_excel(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, thousands, comment, skipfooter, convert_float, mangle_dupe_cols, storage_options)
    334     if not isinstance(io, ExcelFile):
    335         should_close = True
--> 336         io = ExcelFile(io, storage_options=storage_options, engine=engine)
    337     elif engine and engine != io.engine:
    338         raise ValueError(

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/excel/_base.py in __init__(self, path_or_buffer, engine, storage_options)
   1069                 ext = "xls"
   1070             else:
-> 1071                 ext = inspect_excel_format(
   1072                     content=path_or_buffer, storage_options=storage_options
   1073                 )

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/excel/_base.py in inspect_excel_format(path, content, storage_options)
    947     assert content_or_path is not None
    948 
--> 949     with get_handle(
    950         content_or_path, "rb", storage_options=storage_options, is_text=False
    951     ) as handle:

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/common.py in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    556 
    557     # open URLs
--> 558     ioargs = _get_filepath_or_buffer(
    559         path_or_buf,
    560         encoding=encoding,

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/common.py in _get_filepath_or_buffer(filepath_or_buffer, encoding, compression, mode, storage_options)
    287                 "storage_options passed with file object or non-fsspec file path"
    288             )
--> 289         req = urlopen(filepath_or_buffer)
    290         content_encoding = req.headers.get("Content-Encoding", None)
    291         if content_encoding == "gzip":

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/common.py in urlopen(*args, **kwargs)
    193     import urllib.request
    194 
--> 195     return urllib.request.urlopen(*args, **kwargs)
    196 
    197 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in open(self, fullurl, data, timeout)
    523 
    524         sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> 525         response = self._open(req, data)
    526 
    527         # post-process response

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in _open(self, req, data)
    540 
    541         protocol = req.type
--> 542         result = self._call_chain(self.handle_open, protocol, protocol +
    543                                   '_open', req)
    544         if result:

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in https_open(self, req)
   1395 
   1396         def https_open(self, req):
-> 1397             return self.do_open(http.client.HTTPSConnection, req,
   1398                 context=self._context, check_hostname=self._check_hostname)
   1399 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1355                           encode_chunked=req.has_header('Transfer-encoding'))
   1356             except OSError as err: # timeout error
-> 1357                 raise URLError(err)
   1358             r = h.getresponse()
   1359         except:

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)>

```

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
SSLCertVerificationError                  Traceback (most recent call last)
/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1353             try:
-> 1354                 h.request(req.get_method(), req.selector, req.data, headers,
   1355                           encode_chunked=req.has_header('Transfer-encoding'))

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1251         """Send a complete request to the server."""
-> 1252         self._send_request(method, url, body, headers, encode_chunked)
   1253 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1297             body = _encode(body, 'body')
-> 1298         self.endheaders(body, encode_chunked=encode_chunked)
   1299 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in endheaders(self, message_body, encode_chunked)
   1246             raise CannotSendHeader()
-> 1247         self._send_output(message_body, encode_chunked=encode_chunked)
   1248 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in _send_output(self, message_body, encode_chunked)
   1006         del self._buffer[:]
-> 1007         self.send(msg)
   1008 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in send(self, data)
    946             if self.auto_open:
--> 947                 self.connect()
    948             else:

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/http/client.py in connect(self)
   1420 
-> 1421             self.sock = self._context.wrap_socket(self.sock,
   1422                                                   server_hostname=server_hostname)

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    499         # ctx._wrap_socket()
--> 500         return self.sslsocket_class._create(
    501             sock=sock,

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/ssl.py in _create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
   1039                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
-> 1040                     self.do_handshake()
   1041             except (OSError, ValueError):

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/ssl.py in do_handshake(self, block)
   1308                 self.settimeout(None)
-> 1309             self._sslobj.do_handshake()
   1310         finally:

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
<ipython-input-4-5b595d75abc1> in <module>
      1 #Pull Biomass excel sheet
      2 path = ('https://forest-observation-system.net/Data/FOS_Plots_v2019.04.10.xlsx')
----> 3 df = pd.read_excel (path)
      4 df.keys()
      5 gdf = gp.GeoDataFrame(

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    297                 )
    298                 warnings.warn(msg, FutureWarning, stacklevel=stacklevel)
--> 299             return func(*args, **kwargs)
    300 
    301         return wrapper

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/excel/_base.py in read_excel(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, thousands, comment, skipfooter, convert_float, mangle_dupe_cols, storage_options)
    334     if not isinstance(io, ExcelFile):
    335         should_close = True
--> 336         io = ExcelFile(io, storage_options=storage_options, engine=engine)
    337     elif engine and engine != io.engine:
    338         raise ValueError(

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/excel/_base.py in __init__(self, path_or_buffer, engine, storage_options)
   1069                 ext = "xls"
   1070             else:
-> 1071                 ext = inspect_excel_format(
   1072                     content=path_or_buffer, storage_options=storage_options
   1073                 )

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/excel/_base.py in inspect_excel_format(path, content, storage_options)
    947     assert content_or_path is not None
    948 
--> 949     with get_handle(
    950         content_or_path, "rb", storage_options=storage_options, is_text=False
    951     ) as handle:

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/common.py in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    556 
    557     # open URLs
--> 558     ioargs = _get_filepath_or_buffer(
    559         path_or_buf,
    560         encoding=encoding,

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/common.py in _get_filepath_or_buffer(filepath_or_buffer, encoding, compression, mode, storage_options)
    287                 "storage_options passed with file object or non-fsspec file path"
    288             )
--> 289         req = urlopen(filepath_or_buffer)
    290         content_encoding = req.headers.get("Content-Encoding", None)
    291         if content_encoding == "gzip":

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/site-packages/pandas/io/common.py in urlopen(*args, **kwargs)
    193     import urllib.request
    194 
--> 195     return urllib.request.urlopen(*args, **kwargs)
    196 
    197 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in open(self, fullurl, data, timeout)
    523 
    524         sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> 525         response = self._open(req, data)
    526 
    527         # post-process response

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in _open(self, req, data)
    540 
    541         protocol = req.type
--> 542         result = self._call_chain(self.handle_open, protocol, protocol +
    543                                   '_open', req)
    544         if result:

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in https_open(self, req)
   1395 
   1396         def https_open(self, req):
-> 1397             return self.do_open(http.client.HTTPSConnection, req,
   1398                 context=self._context, check_hostname=self._check_hostname)
   1399 

/opt/conda/envs/eurodatacube-0.24.5/lib/python3.8/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1355                           encode_chunked=req.has_header('Transfer-encoding'))
   1356             except OSError as err: # timeout error
-> 1357                 raise URLError(err)
   1358             r = h.getresponse()
   1359         except:

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)>

```

**Comment by totycro** [comment]
I've contacted the author to fix the invalid ssl cert.

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Comment by eurodatacube-submissions** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [7]":
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-4008a60e3c22> in <module>
      3 reference_path = os.environ['EDC_PATH']  + '/data/biomass/Biomass_tiff/'
      4 #print(os.listdir(reference_path))
----> 5 aoi_ids = [i.replace('.tif','').replace('patch_', '') for i in os.listdir(reference_path) if '.tif' in i]
      6 aoi_ids = ['ALP-02_0_3',
      7  'ALP-02_0_2',

FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/.shared/notebooks/eurodatacube/data/biomass/Biomass_tiff/'

```

**Comment by eurodatacube-submissions** [comment]
The notebook was executed sucessfully :heavy_check_mark:

**Pull request merged**
