### PR TITLE
Add Detect_trucks_sentinel2_COVID19.ipynb (ID: 4d8309c3-d77f-46b6-b339-cad19328ad50)

### PR DESCRIPTION
**Pull request by totycro**
{"path": "Detect_trucks_sentinel2_COVID19.ipynb", "id": "4d8309c3-d77f-46b6-b339-cad19328ad50", "license": null, "name": "Truck Detection with Sentinel-2 during COVID19 crisis", "requirements": ["eurodatacube"], "tags": ["COVID-19"], "tosAgree": true, "type": "Jupyter Notebook", "user_id": "0c0a0ef4-8d0d-4e70-b002-033c7cbb41fd", "version": "0.0.1", "description": "Truck Detection with Sentinel-2 during COVID19 crisis"}

### CODE REVIEW

**Comment by Scartography** [comment]
The Example [https://github.com/hfisser/Truck_Detection_Sentinel2_COVID19]( https://github.com/hfisser/Truck_Detection_Sentinel2_COVID19) seems to have a lot of false positives as is (Ships, storage tanks in the harbor, etc. use at least some basic vector data as auxiliary datasets). Also in the javascript for Sentinel-Hub the thresholds need to be adjusted every single time. As is the script is just a alternation/extension of [NDBI](https://www.arcgis.com/home/item.html?id=3cf4e98f035e47279091dc74d43392a5) of sorts.

**Comment by totycro** [comment]
:x: The execution resulted in errors:\n```
---------------------------------------------------------------------------
Exception encountered at "In [6]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-79e0718e19ff> in <module>
      6                       time_range = [dates[-2], dates[-1]],
      7                       time_period = time_period)
----> 8 cube = open_cube(cube_con)
      9 scl = MaskSet(cube.SCL)
     10 cube = cube.where((scl.clouds_high_probability) == 0)

/opt/conda/lib/python3.7/site-packages/xcube_sh/cube.py in open_cube(cube_config, observer, trace_store_calls, max_cache_size, **sh_kwargs)
     47     :return: the data cube represented by an xarray Dataset object.
     48     """
---> 49     sentinel_hub = SentinelHub(**sh_kwargs)
     50     cube_store = SentinelHubStore(sentinel_hub, cube_config, observer=observer, trace_store_calls=trace_store_calls)
     51     if max_cache_size:

/opt/conda/lib/python3.7/site-packages/xcube_sh/sentinelhub.py in __init__(self, client_id, client_secret, instance_id, api_url, oauth2_url, enable_warnings, error_policy, error_handler, num_retries, retry_backoff_max, retry_backoff_base, session)
     90 
     91             if not client_id or not client_secret:
---> 92                 raise ValueError('Both client_id and client_secret must be provided.\n'
     93                                  'Consider setting environment variables SH_CLIENT_ID and SH_CLIENT_SECRET.\n'
     94                                  'For more information refer to '

ValueError: Both client_id and client_secret must be provided.
Consider setting environment variables SH_CLIENT_ID and SH_CLIENT_SECRET.
For more information refer to https://docs.sentinel-hub.com/api/latest/#/API/authentication
\n```

**Comment by totycro** [comment]
:x: The execution resulted in errors:
```
---------------------------------------------------------------------------
Exception encountered at "In [9]":
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/xarray/backends/file_manager.py in _acquire_with_cache_info(self, needs_lock)
    197             try:
--> 198                 file = self._cache[self._key]
    199             except KeyError:

/opt/conda/lib/python3.7/site-packages/xarray/backends/lru_cache.py in __getitem__(self, key)
     52         with self._lock:
---> 53             value = self._cache[key]
     54             self._cache.move_to_end(key)

KeyError: [<function _open_scipy_netcdf at 0x7f016afd0440>, ('/home/jovyan/roads_mask_example_2020-04-20.nc',), 'a', (('mmap', None), ('version', 2))]

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-9-2ec3a725178d> in <module>
      1 roads_mask.plot.imshow(vmin = 0, vmax = 1, cmap = "binary", figsize = [16, 8])
----> 2 roads_mask.to_netcdf("roads_mask_example_" + date + ".nc")

/opt/conda/lib/python3.7/site-packages/xarray/core/dataarray.py in to_netcdf(self, *args, **kwargs)
   2351             dataset = self.to_dataset()
   2352 
-> 2353         return dataset.to_netcdf(*args, **kwargs)
   2354 
   2355     def to_dict(self, data: bool = True) -> dict:

/opt/conda/lib/python3.7/site-packages/xarray/core/dataset.py in to_netcdf(self, path, mode, format, group, engine, encoding, unlimited_dims, compute, invalid_netcdf)
   1543             unlimited_dims=unlimited_dims,
   1544             compute=compute,
-> 1545             invalid_netcdf=invalid_netcdf,
   1546         )
   1547 

/opt/conda/lib/python3.7/site-packages/xarray/backends/api.py in to_netcdf(dataset, path_or_file, mode, format, group, engine, encoding, unlimited_dims, compute, multifile, invalid_netcdf)
   1087         # to be parallelized with dask
   1088         dump_to_store(
-> 1089             dataset, store, writer, encoding=encoding, unlimited_dims=unlimited_dims
   1090         )
   1091         if autoclose:

/opt/conda/lib/python3.7/site-packages/xarray/backends/api.py in dump_to_store(dataset, store, writer, encoder, encoding, unlimited_dims)
   1133         variables, attrs = encoder(variables, attrs)
   1134 
-> 1135     store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
   1136 
   1137 

/opt/conda/lib/python3.7/site-packages/xarray/backends/common.py in store(self, variables, attributes, check_encoding_set, writer, unlimited_dims)
    294 
    295         self.set_attributes(attributes)
--> 296         self.set_dimensions(variables, unlimited_dims=unlimited_dims)
    297         self.set_variables(
    298             variables, check_encoding_set, writer, unlimited_dims=unlimited_dims

/opt/conda/lib/python3.7/site-packages/xarray/backends/common.py in set_dimensions(self, variables, unlimited_dims)
    355             unlimited_dims = set()
    356 
--> 357         existing_dims = self.get_dimensions()
    358 
    359         dims = {}

/opt/conda/lib/python3.7/site-packages/xarray/backends/scipy_.py in get_dimensions(self)
    162 
    163     def get_dimensions(self):
--> 164         return Frozen(self.ds.dimensions)
    165 
    166     def get_encoding(self):

/opt/conda/lib/python3.7/site-packages/xarray/backends/scipy_.py in ds(self)
    144     @property
    145     def ds(self):
--> 146         return self._manager.acquire()
    147 
    148     def open_store_variable(self, name, var):

/opt/conda/lib/python3.7/site-packages/xarray/backends/file_manager.py in acquire(self, needs_lock)
    178         An open file object, as returned by ``opener(*args, **kwargs)``.
    179         """
--> 180         file, _ = self._acquire_with_cache_info(needs_lock)
    181         return file
    182 

/opt/conda/lib/python3.7/site-packages/xarray/backends/file_manager.py in _acquire_with_cache_info(self, needs_lock)
    202                     kwargs = kwargs.copy()
    203                     kwargs["mode"] = self._mode
--> 204                 file = self._opener(*self._args, **kwargs)
    205                 if self._mode == "w":
    206                     # ensure file doesn't get overriden when opened again

/opt/conda/lib/python3.7/site-packages/xarray/backends/scipy_.py in _open_scipy_netcdf(filename, mode, mmap, version)
     81 
     82     try:
---> 83         return scipy.io.netcdf_file(filename, mode=mode, mmap=mmap, version=version)
     84     except TypeError as e:  # netcdf3 message is obscure in this case
     85         errmsg = e.args[0]

/opt/conda/lib/python3.7/site-packages/scipy/io/netcdf.py in __init__(self, filename, mode, mmap, version, maskandscale)
    250             self.filename = filename
    251             omode = 'r+' if mode == 'a' else mode
--> 252             self.fp = open(self.filename, '%sb' % omode)
    253             if mmap is None:
    254                 # Mmapped files on PyPy cannot be usually closed

OSError: [Errno 30] Read-only file system: '/home/jovyan/roads_mask_example_2020-04-20.nc'

```

**Comment by totycro** [comment]
:x: Execution timed out after 180 seconds

**Comment by totycro** [comment]
Not accepting submission since its execution takes too long

**Pull request closed without merging**
